version: '3'

services:
  app:
    container_name: your_app_name
    build:
      dockerfile: .docker/Dockerfile.prod
      context: .
    working_dir: /data/app
    ports:
      - '80'
    volumes:
      - ./:/data/app
      - static_volume:/data/app/static
    environment:
      - VIRTUAL_HOST=kidsapp.kyoto-su.ac.jp
      - VIRTUAL_PATH=/your_app_name/
      - VIRTUAL_DEST=/
    env_file:
      - .env/.env.prod
    depends_on:
      your_app_name_db:
        condition: service_healthy

  your_app_name_db:
    container_name: your_app_name_db
    image: postgres
    ports:
      - '5432'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - your_app_name_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pos.pos..pos
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres
    healthcheck:
      test: psql -U ${POSTGRES_USER:-postgres} -c SELECT your_app_name
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  default:
    name: kidsapp-server
    external: true

volumes:
  your_app_name_db_volume:
  static_volume:
    external: true